spring.application.name=content
spring.datasource.url=${DB_Url}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${MariaDB_Password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${Mail_UserName}
spring.mail.password=${Mail_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis ??
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=your_redis_password
spring.data.redis.database=0


# AWS S3 Configuration
# --- AWS ?? ?? (IAM ??? Access Key) ---
cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secretKey=${AWS_SECRET_ACCESS_KEY}

# --- AWS ?? ?? ---
cloud.aws.region.static=ap-southeast-2
cloud.aws.s3.bucketName=lococoimg

# --- AWS CloudFormation ?? ?? ?? ???? ---
cloud.aws.stack.auto=false

# ??? ?? ?? ?? ??
spring.config.import=optional:application-secret.properties